### ISSUE TITLE
Authentication for the front end app

### ISSUE THREAD

**Issue by docsteveharris** [HYLODE/HyUi#262]
You will need to add some form of authentication to be able to share this beyond the existing user group
Try this https://dmc-dbc-building-blocks.onrender.com/authentication

And some other community tips here

https://community.plotly.com/t/dash-app-pages-with-flask-login-flow-using-flask/69507
https://github.com/orgs/HYLODE/projects/1/views/15?pane=issue&itemId=21766376
https://github.com/tzelleke/flask-dash-app
https://github.com/gaw89/dash-flask-login

We have done this before on last year's version

**Comment by harryjmoss** [comment]
Will consider https://github.com/plotly/dash-auth also
