### ISSUE TITLE
Indicate blocked bays/beds

### ISSUE THREAD

**Issue by docsteveharris** [HYLODE/HyUi#263]
We should make the blocked beds and bays design language clear
I think this is quite a quick fix

- [x] Suggest 'grey' out beds 
- [x] And make them non-selectable
- [x] Prob should stop the user being able to move the beds independently too
- [x] and fresh chevron design for the 'ready'/'review'

**Comment by hqva** [comment]
Is there any front-end way of closing the bed?

I can only it live on the T06 beds - I like the greyed out octagon but don't know if it's too subtle?

approve of the changes so far though
