### ISSUE TITLE
Collate all docs/links into a single place

### ISSUE THREAD

**Issue by docsteveharris** [HYLODE/HyUi#278]
There's extensive documentation scattered across the `readme.md` files in https://github.com/HYLODE/HySys/tree/main/hylode. I don't know if it's worth moving these but I think there should be pointers in http://hylode.org/user/user.html (i.e. `https://github.com/HYLODE/HyUi/tree/main/docs`) to cover key tasks

For example, I just merged a pull request on hysys but might not know where

- hysys is deployed
- that there's a script to bring it down and back up again etc.

I suspect there's a small list of common tasks that we could describe, and then either provide docs directly or point to the appropriate readme.

**Comment by harryjmoss** [comment]
Will be closed by HYLODE/Hyui#279 and HYLODE/HySys#574
